[workspace]
resolver = "2"
members = [
    "cmd/stellar-rpc/lib/preflight",
    "cmd/stellar-rpc/lib/ffi",
    "cmd/stellar-rpc/lib/xdr2json"
]

[workspace.package]
rust-version = "1.79.0"

[workspace.dependencies.soroban-env-host-prev]
package = "soroban-env-host"
version = "=25.0.1"

[workspace.dependencies.soroban-env-host-curr]
package = "soroban-env-host"
git = "https://github.com/stellar/rs-soroban-env.git"

[workspace.dependencies.soroban-simulation-prev]
package = "soroban-simulation"
version = "=25.0.1"

[workspace.dependencies.soroban-simulation-curr]
package = "soroban-simulation"
git = "https://github.com/stellar/rs-soroban-env.git"
features = [ "unstable-next-api" ]

[workspace.dependencies.stellar-xdr]
version = "=25.0.0"
git = "https://github.com/stellar/rs-stellar-xdr.git"
rev = "c458ac6bb943c271332cb8cf274b492433cb763f"
features = [ "serde", "next" ]

[workspace.dependencies]
base64 = "0.22.0"
sha2 = "0.10.7"
libc = "0.2.147"
anyhow = "1.0.75"
rand = { version = "0.8.5", features = [] }
serde_json = "1.0"

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
