[workspace]
resolver = "2"
members = [
    "cmd/stellar-rpc/lib/preflight",
    "cmd/stellar-rpc/lib/ffi",
    "cmd/stellar-rpc/lib/xdr2json"
]

[workspace.package]
rust-version = "1.79.0"

[workspace.dependencies.soroban-env-host-prev]
package = "soroban-env-host"
version = "=22.1.4"

[workspace.dependencies.soroban-env-host-curr]
package = "soroban-env-host"
version = "=23.0.0-rc.1.1"

[workspace.dependencies.soroban-simulation-prev]
package = "soroban-simulation"
version = "=22.1.4"

[workspace.dependencies.soroban-simulation-curr]
package = "soroban-simulation"
version = "=23.0.0-rc.1.1"

[patch.crates-io]
soroban-simulation = { version = "=23.0.0-rc.1.1", git = "https://github.com/stellar/rs-soroban-env", rev = "8e774962ad2f1c7b9a8b4362cea6cc144391f2df" }
soroban-env-host = { version = "=23.0.0-rc.1.1", git = "https://github.com/stellar/rs-soroban-env", rev = "8e774962ad2f1c7b9a8b4362cea6cc144391f2df" }

[workspace.dependencies.stellar-xdr]
version = "=23.0.0-rc.1"
features = [ "serde" ]

[workspace.dependencies]
base64 = "0.22.0"
sha2 = "0.10.7"
libc = "0.2.147"
anyhow = "1.0.75"
rand = { version = "0.8.5", features = [] }
serde_json = "1.0"

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
